name: Build and Vendor Go Modules

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout


on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::168437900419:role/oidc-github-role
          role-session-name: samplerolesession
          aws-region: ca-central-1
         
      - name: Request and Print OIDC token
        run: |
          echo "Fetching OIDC token..."
          TOKEN_VALUE=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
          echo "GitHub OIDC Token:"
          echo "$TOKEN_VALUE" | cut -d "." -f2 | base64 -d | jq


      # - name: Set Up Git Credentials for Private Modules
      #   run: |
      #     git config --global url."https://${{ secrets.TOKEN }}@github.com/CloudReady-club/".insteadOf "https://github.com/CloudReady-club/"


      # - name: Set Up Go Environment
      #   run: |
      #     go env -w GOPRIVATE="github.com/CloudReady-club/*"

      # - name: Install Dependencies and Vendor
      #   run: |
      #     go mod tidy
      #     go mod vendor

      # - name: Build Project
      #   run: |
      #     go build -o app .
