name: Build and Vendor Go Modules

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::816069145650:role/github-test
          role-session-name: samplerolesession
          aws-region: ca-central-1

      - name: Set Up Git Credentials for Private Modules
        run: |
          git config --global url."https://${{ secrets.TOKEN }}@github.com/CloudReady-club/".insteadOf "https://github.com/CloudReady-club/"


      - name: Set Up Go Environment
        run: |
          go env -w GOPRIVATE="github.com/CloudReady-club/*"

      - name: Install Dependencies and Vendor
        run: |
          go mod tidy
          go mod vendor

      - name: Build Project
        run: |
          go build -o app .
